name: ps5-pup-decrypt

on:
  push:
    paths:
      - '**'
  workflow_dispatch:

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  payload-build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc-9 g++-9 make

    - name: Build Unpacker
      run: |
        make

    - name: Attest
      uses: actions/attest-build-provenance@v1
      continue-on-error: true  # this will fail if the repo is private
      with: 
        subject-path: ./ps5_pup_decrypt.elf

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ps5-pup-decrypt
        path: ./ps5_pup_decrypt.elf
        if-no-files-found: error
